attempt 2 to update to version 1.19

diff --git a/.github/workflows/pretty.yml b/.github/workflows/pretty.yml
--- a/.github/workflows/pretty.yml
+++ b/.github/workflows/pretty.yml
@@ -5,128 +5,129 @@ jobs:
     name: Build
     runs-on: ubuntu-latest
     steps:
-    #start of new code to try to fix error
-    - name: Install Apptainer
-      run: |
-      sudo apt-get update && sudo apt-get install -y \
-        build-essential \
-        libseccomp-dev \
-        pkg-config \
-        squashfs-tools \
-        cryptsetup \
-        curl \
-        git \
-        uuid-dev \
-        libgpgme-dev \
-        libssl-dev \
-        libglib2.0-dev \
-        libseccomp-dev \
-        wget \
-        runc
+      # start of new code to try to fix error
+      - name: Install Apptainer
+        run: |
+          sudo apt-get update && sudo apt-get install -y \
+            build-essential \
+            libseccomp-dev \
+            pkg-config \
+            squashfs-tools \
+            cryptsetup \
+            curl \
+            git \
+            uuid-dev \
+            libgpgme-dev \
+            libssl-dev \
+            libglib2.0-dev \
+            libseccomp-dev \
+            wget \
+            runc
 
-        export VERSION=1.1.6  # or latest release
-        wget https://github.com/apptainer/apptainer/releases/download/v${VERSION}/apptainer_${VERSION}_amd64.deb
-        sudo dpkg -i apptainer_${VERSION}_amd64.deb
-#end of new code
-    - name: Check out code
-      uses: actions/checkout@v2
-      
-    - name: Install useful utilities
-      run: sudo apt-get install -y tree
+          export VERSION=1.1.6  # or latest release
+          wget https://github.com/apptainer/apptainer/releases/download/v${VERSION}/apptainer_${VERSION}_amd64.deb
+          sudo dpkg -i apptainer_${VERSION}_amd64.deb
+      # end of new code
 
-    - name: Checking if LICENSE exists
-      run: |
-        FILE=LICENSE
-        if [ -f "$FILE" ]; then
-            echo "File "$FILE" exists."
-            exit 0
-        else 
-            echo "File $FILE does not exist."
-            exit 1
-        fi
+      - name: Check out code
+        uses: actions/checkout@v2
 
-    - name: Checking if Apache License Version 2.0, January 2004 is being used
-      run: |
-        if grep --quiet "Apache License" LICENSE && grep --quiet "Version 2.0, January 2004" LICENSE; then
-            echo "Using Apache License Version 2.0, January 2004"
-            exit 0
-        else
-            echo "Not using Apache License Version 2.0, January 2004"
-            exit 1
-        fi
-    
-    - name: Checking if CONTRIBUTING guide exists
-      run: |
-        FILE=CONTRIBUTING.md
-        if [ -f "$FILE" ]; then
-            echo "File "$FILE" exists."
-            exit 0
-        else 
-            echo "File $FILE does not exist."
-            exit 1
-        fi
+      - name: Install useful utilities
+        run: sudo apt-get install -y tree
 
-    - name: Checking if README file exists
-      run: |
-        FILE=README.md
-        if [ -f "$FILE" ]; then
-            echo "File "$FILE" exists."
-            exit 0
-        else 
-            echo "File $FILE does not exist."
-            exit 1
-        fi
-    
-    - name: Checking if copyrighted to Pittsburgh Supercomputing Center
-      run: |
-        if grep --quiet "Pittsburgh Supercomputing Center. All Rights Reserved." README.md; then
-            echo "Copyright (c) Pittsburgh Supercomputing Center"
-            exit 0
-        else
-            echo "No reference to Pittsburgh Supercomputing Center"
-            exit 1
-        fi
+      - name: Checking if LICENSE exists
+        run: |
+          FILE=LICENSE
+          if [ -f "$FILE" ]; then
+              echo "File "$FILE" exists."
+              exit 0
+          else 
+              echo "File $FILE does not exist."
+              exit 1
+          fi
 
-    - name: Checking if there exists at least one Singularity definition file
-      run: |
-        FILE=Singularity
-        if [ $(find . -name "$FILE" -mmin -5 | wc -l) -gt 0 ]; then 
-            echo "File "$FILE" was found.";
-            exit 0 
-        else 
-            echo "File "$FILE" was not found.";
-            exit 1
-        fi
+      - name: Checking if Apache License Version 2.0, January 2004 is being used
+        run: |
+          if grep --quiet "Apache License" LICENSE && grep --quiet "Version 2.0, January 2004" LICENSE; then
+              echo "Using Apache License Version 2.0, January 2004"
+              exit 0
+          else
+              echo "Not using Apache License Version 2.0, January 2004"
+              exit 1
+          fi
 
-    - name: Checking if there exists at least one build script
-      run: |
-        FILE=build.sh
-        if [ $(find . -name "$FILE" -mmin -5 | wc -l) -gt 0 ]; then 
-            echo "File "$FILE" was found.";
-            exit 0 
-        else 
-            echo "File "$FILE" was not found.";
-            exit 1
-        fi
+      - name: Checking if CONTRIBUTING guide exists
+        run: |
+          FILE=CONTRIBUTING.md
+          if [ -f "$FILE" ]; then
+              echo "File "$FILE" exists."
+              exit 0
+          else 
+              echo "File $FILE does not exist."
+              exit 1
+          fi
 
-    - name: Checking if there exists at least one remote build script
-      run: |
-        FILE=rbuild.sh
-        if [ $(find . -name "$FILE" -mmin -5 | wc -l) -gt 0 ]; then 
-            echo "File "$FILE" was found.";
-            exit 0 
-        else 
-            echo "File "$FILE" was not found.";
-            exit 1
-        fi
+      - name: Checking if README file exists
+        run: |
+          FILE=README.md
+          if [ -f "$FILE" ]; then
+              echo "File "$FILE" exists."
+              exit 0
+          else 
+              echo "File $FILE does not exist."
+              exit 1
+          fi
 
-    - name: Checking if there exists at least one test script
-      run: |
-        FILE=test.sh
-        if [ $(find . -name "$FILE" -mmin -5 | wc -l) -gt 0 ]; then 
-            echo "File "$FILE" was found.";
-            exit 0 
-        else 
-            echo "File "$FILE" was not found.";
-            exit 1
-        fi
+      - name: Checking if copyrighted to Pittsburgh Supercomputing Center
+        run: |
+          if grep --quiet "Pittsburgh Supercomputing Center. All Rights Reserved." README.md; then
+              echo "Copyright (c) Pittsburgh Supercomputing Center"
+              exit 0
+          else
+              echo "No reference to Pittsburgh Supercomputing Center"
+              exit 1
+          fi
+
+      - name: Checking if there exists at least one Singularity definition file
+        run: |
+          FILE=Singularity
+          if [ $(find . -name "$FILE" -mmin -5 | wc -l) -gt 0 ]; then 
+              echo "File "$FILE" was found.";
+              exit 0 
+          else 
+              echo "File "$FILE" was not found.";
+              exit 1
+          fi
+
+      - name: Checking if there exists at least one build script
+        run: |
+          FILE=build.sh
+          if [ $(find . -name "$FILE" -mmin -5 | wc -l) -gt 0 ]; then 
+              echo "File "$FILE" was found.";
+              exit 0 
+          else 
+              echo "File "$FILE" was not found.";
+              exit 1
+          fi
+
+      - name: Checking if there exists at least one remote build script
+        run: |
+          FILE=rbuild.sh
+          if [ $(find . -name "$FILE" -mmin -5 | wc -l) -gt 0 ]; then 
+              echo "File "$FILE" was found.";
+              exit 0 
+          else 
+              echo "File "$FILE" was not found.";
+              exit 1
+          fi
+
+      - name: Checking if there exists at least one test script
+        run: |
+          FILE=test.sh
+          if [ $(find . -name "$FILE" -mmin -5 | wc -l) -gt 0 ]; then 
+              echo "File "$FILE" was found.";
+              exit 0 
+          else 
+              echo "File "$FILE" was not found.";
+              exit 1
+          fi
